#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(as_float: true));

require __DIR__.'/vendor/autoload.php';

/** @var Application $app */
$app    = require __DIR__ . '/bootstrap/app.php';
$status = $app->handleCommand(input: new ArgvInput);

exit($status);
